### PR TITLE
refactor: Capitalise all column and table names 

### PR DESCRIPTION
**Pull request by andyatterton**
Worth you all being aware of this. In theory, it shouldn't be breaking as I don't think SQLA cares about capitalisation (after all we have been using lower case when in fact the DB is all in upper) but I have run into issues with then matching them to entries from the RR_DATA_DEFINTION tables which list all table and column names in capital.

Hopefully you are all in agreement that the models should as much as possible reflect the tables. There are many areas where this is not the case but we can come back to that later.

### CODE REVIEW

**Comment by George-D-S** [comment]
> In theory, it shouldn't be breaking as I don't think SQLA cares about capitalisation (after all we have been using lower case when in fact the DB is all in upper)

I think it's more correct to say that SQL Server doesn't care about capitalisation so will accept whatever it's given. When we tried the same on Oracle it didn't work ( See https://github.com/renalreg/ukrr_rda_extract/blob/6f765d6dd91c8eb6c08a711e5f6530d476dfd647/ukrdc/ukrr_extract/xml_utils.py#L20 ).

**Review by George-D-S — APPROVED** [review]

**Comment by andyatterton** [comment]
Yeah, I did notice this comment and was planning on removing it as I don't think any of our current databases care about capitalisation, but I do fear for time travelling George. I would assume though that the you that would arrive in the past having gone through the portal would do so with his memories intact.

**Review by GlebRysev-UKKA — APPROVED** [review]

**Review by philmain28 — COMMENTED** [review]
Not sure I sure I use these models so don't particularly have a horse in this race but my preference would be using the synonym construct here as an easy way to allow some backwards compatibility: 
https://docs.sqlalchemy.org/en/20/orm/mapped_attributes.html#synonyms

The only other thing I have to add is that some of the tables are mirrored in the ukrdc for example rr_data_definition and I have found it useful having one model that can query both in the past.

**Review by andreeoap — APPROVED** [review]
noted! thanks Andy, I understand the change to uppercase is only for consistency and won't have any functional effect as long as the SQL Server db uses a case-insensitive collation (like the current default one).

**Pull request merged**
