### PR TITLE
fix(nhsbt): :bug: Corrected column types

### PR DESCRIPTION
**Pull request by andyatterton**
All of the columns recording dates were of type date and should be datetime to accuratly mirror the database. Also changed the bit column to a boolean as I believe this to be the correct way to map that column type.

### CODE REVIEW

**Comment by andyatterton** [comment]
Because sometimes the time is important. Bad idea for dates of birth (unless you really want to know birth time) but for transplants that could have more than one occurrence in a single day the time is relevant.

Pretty sure datetime handles daylight savings with timedeltas + 1hour

**Comment by philmain28** [comment]
Mmmm yeah I understand that datetimes are appropriate in circumstances where the time is important but it seems like it adds an additional potential source of error if not.

**Comment by andyatterton** [comment]
I wouldn't personally of used date times for most of it, especially considering this is being delivered via CSV and doesn't come with any time stamps, but I suppose in a world where we might one day receive date times through an automatic feed it could be considered future proofing

**Review by philmain28 — APPROVED** [review]

**Comment by George-D-S** [comment]
Some of the field choices in the "renalreg" database are explained by the structure having been a conversion of the preceeding Oracle database - if the date/datetime fields aren't what one might have chosen you should see how the numeric values are being stored.

**Review by George-D-S — APPROVED** [review]

**Pull request merged**
